### PR TITLE
Submit RWS for Zalo

### PR DESCRIPTION
**Pull request by kldz1412**
Add RWS for Zalo Group

### CODE REVIEW

**Review by sjledoux — APPROVED** [review]
LGTM, merging.

**Comment by Parasos** [comment]
related_website_sets.JSON

**Comment by Parasos** [comment]
RwsCheck.py

**Comment by Parasos** [comment]
related_website_sets.JSON

**Review by Parasos — COMMENTED** [review]
related_website_sets.JSON

**Pull request merged**
