### PR TITLE
Be more specific about expected schema validation failures

### PR DESCRIPTION
**Pull request by cfredric**
This ensures that validation fails for the right reason, i.e. that we're testing the thing that we intend to be testing.

### CODE REVIEW

**Review by arichiv — APPROVED** [review]

**Review by sjledoux — APPROVED** [review]
LGTM

**Review by kuba736 — APPROVED** [review]

**Comment by samanmokhtarzadeh** [comment]
e006237e96a9e2577d9980fb8090c46b296f3055

**Comment by samanmokhtarzadeh** [comment]
> LGTM

**Review by samanmokhtarzadeh — APPROVED** [review]

**Review by samanmokhtarzadeh — APPROVED** [review]

**Comment by samanmokhtarzadeh** [comment]
e006237e96a9e2577d9980fb8090c46b296f3055d0877c99b38bb4c61d29ed92b00a026718ac43d1

**Pull request merged**
