### PR TITLE
Update related_website_sets.JSON

### PR DESCRIPTION
**Pull request by SirBond**

### CODE REVIEW

**Review by aselya — APPROVED** [review]
LGTM merging

**Comment by aselya** [comment]
Unfortunately, this pull request had conflicts that we do not have the permissions necessary to address. This [website](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork#enabling-repository-maintainer-permissions-on-existing-pull-requests) has instructions that you can follow to give us the permissions necessary to assist you directly. Or if you'd prefer you can address the conflicts yourself.

**Comment by SirBond** [comment]
Please, Allow edits by maintainers, is this what is needed?

**Comment by Airborn22** [comment]
Hi @SirBond,
Yes, that's the permission we needed. I was able to resolve the merge conflicts, going to merge the CL now

**Comment by SirBond** [comment]
Thank you :)

**Pull request merged**
