### PR TITLE
Add Drimer RWS record

### PR DESCRIPTION
**Pull request by nmaletm**

### CODE REVIEW

**Review by aselya — APPROVED** [review]
LGTM merging!

**Comment by ratchanonsuttawas** [comment]
28583e3bf61c9c6281be5c3d27de8ea970d22ac2

**Comment by ratchanonsuttawas** [comment]
fb06c7a75b9cfbdfd1139e6e9eddf814387f804e

**Comment by ratchanonsuttawas** [comment]
fb06c7a75b9cfbdfd1139e6e9eddf814387f804e

**Comment by ratchanonsuttawas** [comment]
> 

Main
fb06c7a75b9cfbdfd1139e6e9eddf814387f804e

**Review by ratchanonsuttawas — COMMENTED** [review]
Changes

**Pull request merged**
