### PR TITLE
rws updates for hc1

### PR DESCRIPTION
**Pull request by lGiridharan**

### CODE REVIEW

**Review by aselya — APPROVED** [review]
LGTM. Merging.

**Comment by aselya** [comment]
Unfortunately, this pull request had conflicts that we do not have the permissions necessary to address. This [website](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork#enabling-repository-maintainer-permissions-on-existing-pull-requests) has instructions that you can follow to give us the permissions necessary to assist you directly. Or if you'd prefer you can address the conflicts yourself.

**Comment by lGiridharan** [comment]
@aselya  All Merge Conflicts are resolved

**Comment by aselya** [comment]
@lGiridharan, thank you for addressing the merge issues so quickly.

**Pull request merged**
