### PR TITLE
[NOT A CONTRIBUTION] - Movement for an Open Web - Initial RWS

### PR DESCRIPTION
**Pull request by movementforanopenweb**

### CODE REVIEW

**Comment by movementforanopenweb** [comment]
Do you know when we should expect this to be reviewed?

**Comment by cfredric** [comment]
Re: expected review timelines, please see "Validation success" under the [technical validation section](https://github.com/GoogleChrome/related-website-sets/blob/main/RWS-Submission_Guidelines.md#subset-level-technical-validation).

For this PR, I'm not reviewing this since it is clearly marked as "not a contribution". Closing.

**Comment by movementforanopenweb** [comment]
@cfredric - it's marked "not a contribution" as per the [CLA](https://cla.developers.google.com/about/google-corporate) to limit the rights granted to Google associated with the submission. That does not mean you can't incorporate the changes in the file if you wish. Please can you re-open and approve?

**Comment by cfredric** [comment]
Hi @movementforanopenweb,

The "not a contribution" designation means it is fundamentally impossible to merge your pull request while simultaneously not treating it as a contribution. Marking a pull request as "not a contribution" is incompatible with the fundamental nature of a pull request.

Furthermore, this PR has other issues that prevent its inclusion in this project including, but not limited to:

1. Some of the "rationale" text is copied and pasted from another site which is protected by the GNU Free Documentation License. Google [does not use](https://opensource.google/documentation/reference/thirdparty/licenses) artifacts protected by licenses of this type.

2. Almost every single site in this PR contains copyright infringements and "lorem ipsum" placeholder text. It is not clear that you have direct ownership of the sites’ content, as attested to by signing the CLA. so we view these sites as problematic for submission.

 We will not reopen this PR. Thank you for understanding.

**Comment by thegreatfatzby** [comment]
Hi @cfredric ! I'm working on a few MSFT Related Web Site integrations and have been reading the docs and issues trying to wrap my head around different pieces. I appreciate all of the hard work you guys have put into iterating on this.

Comparing the [submission requirements](https://github.com/GoogleChrome/related-website-sets/blob/main/RWS-Submission_Guidelines.md) to the rejection reasons here, I need some clarification w/r/t Google's role in the [enforcement process](https://github.com/GoogleChrome/related-website-sets/blob/main/RWS-Submission_Guidelines.md#enforcement-activities). From the enforcement section (highlighting mine):

> At this time, _validation of set submissions will be based on the methods described in these Guidelines_, _**and Chrome will not apply additional enforcement activity governing set submissions**_, however _Chrome reserves the right to act in cases of **egregious and blatant disregard** of these Guidelines_. All submissions are publicly visible and subject to the scrutiny of the broader web community, including users, civil society, and other interested parties.

The "Validation failure" section lists set and subset level technical checks as reasons for failure, and reading through those sections they all look technical (i.e. not editorial, normative, etc). I also don't think I see anything described elsewhere in the document indicating subjectivity outside of the "egregious and blatant disregard" section. I don't believe I've seen anything in other docs, although I'm still grok'ing them.

So please help me understand the precedents implied here better, so that I can help guide Microsoft integrations, including our integrations with 3rd party publishers:
1. **Ownership**: How was "(unclear) direct ownership" in this case determined? My understanding is that the .well-known files are the way that ownership is enforced, indicated in the FAQs [here](https://github.com/GoogleChrome/related-website-sets/blob/main/Getting-Started.md#q-since-anyone-can-contribute-to-the-rws-list-can-someone-else-modify-or-delete-my-rws). I spot checked the primary and a few of the associated well-knowns and they seem to agree with this submission. Is there another heuristic Microsoft needs to be aware of?
2. **Copyright Infringement**: are scans for copyrighted material part of the process, including verifying that those copyrights aren't held by the submitter? If they are, can they be published along along side the submission? 
3. **Lorem Ipsum**: what is the issue here? Lorem ipsum is broadly used in publishing, editorial, and other industries for unobtrusive scaffolding for presentations. 
4. **Open Source**: this one is interesting...I would think the OS guidelines are intended to prevent code from being improperly imported into other code projects. Verbiage intended as an explanation, that doesn't violate an obvious copyright ("Just Do It", "Think Different") seems an odd application. It wouldn't surprise me if boilerplate is used frequently for these reasons so understanding the restrictions here is valuable.
5. **Not a Contribution**: TBH I can see how this might be inferred to have an adversarial stance, even if not intended that way. My guess is that this would refer back to the "egregious and blatant disregard", as it could be seen as trying to avoid commitment to a ToS. If that's the case, it should be stated in the rejection.
6. **Opportunity to Fix**: for all except (5), if these are to be standards by which a submission is judged, how is a submitter to fix? Should they re-submit?
7. **Co-branding**: Not mentioned in your comment, but I am not clear on the need for co-branding. As far as I can tell the submissions here are roughly as co-branded as some of what I'm seeing in the [list](https://github.com/GoogleChrome/related-website-sets/blob/main/related_website_sets.JSON#L280C19-L280C43) associated with https://timesinternet.in.

Depending on the answers to those questions, I would definitely recommend an update to the submission guidelines.

**Comment by thegreatfatzby** [comment]
Hey @movementforanopenweb I'd like to understand your concerns on the rights piece a bit better:

> limit the rights granted to Google associated with the submission

Is there a concern that Google would have some rights over the websites, domains, etc, themselves? If so, maybe Google can state that explicitly by updating something somewhere, as I would imagine/hope that is not their intention.

**Comment by movementforanopenweb** [comment]
@thegreatfatzby as any developer entering into a legal agreement would, we sought legal advice concerning the [Google CLA](https://cla.developers.google.com/about/google-individual).

"Not a Contribution" is defined term in the CLA. See extract with emphasis added.

> "Contribution" shall mean any original work of authorship, including any modifications or additions to an existing work, that is intentionally submitted by You to Google for inclusion in, or documentation of, any of the products owned or managed by Google (the "Work"). For the purposes of this definition, "submitted" means any form of electronic, verbal, or written communication sent to Google or its representatives, including but not limited to communication on electronic mailing lists, source code control systems, and issue tracking systems that are managed by, or on behalf of, Google for the purpose of discussing and improving the Work, but excluding communication that is conspicuously marked or otherwise designated in writing by You as "**Not a Contribution**."

Any communication with a Google employee or contractor in any form that is not marked "Not a Contribution" is covered by the broad terms of the CLA which include granting irrevocable copyright and patent rights globally and in perpetuity. 

We do not think this is reasonable, The CLA is one sided in Google's favour. We wished to limit our risk, as any developer, publisher, or advertiser would, and prevent these CLA provisions being associated with any communication with Google including this submission.

As such for all practical purposes Related Website Sets is unusable in its current implementation.

**Comment by thegreatfatzby** [comment]
Hey @cfredric any thoughts here?

**Comment by cfredric** [comment]
@thegreatfatzby thank you for asking about this. As RWS is an ongoing project and we are continuing to receive new submissions, aspects of the process and our criteria are still being solidified. We do agree that it is important for our submission guidelines to fully outline our requirements for submission, and we will add greater detail to our submission guidelines going forward to avoid further ambiguity and confusion. 

Our intent is for the submission process to be as technical as possible so that we can phase out human involvement and entirely rely on automated checks. PRs such as this one necessitate more human interaction because they include behaviors we did not anticipate, but they allow us to identify more areas for automation and ways we can fix our guidelines to avoid these problems going forward. 

To address your first 3 concerns (Ownership, Copyright, Lorem Ipsum), our reasoning for rejecting the PR at the time was the presence of “NOT A CONTRIBUTION" in the title, as well as the licensing of the rationale text. These other issues we mentioned were aspects of the submission we saw as unusual, but they would not be reasons to exclude this submission from the RWS repo. In MOW’s next submission, some of these behaviors still existed but [we did not cite them in the rejection](https://github.com/GoogleChrome/related-website-sets/pull/202#issuecomment-1883431954). 

> Open Source … I would think the OS guidelines are intended to prevent code from being improperly imported into other code projects.

The issue here was that since the submissions are ingested by various aspects of Google Chrome’s codebase, we cannot accept artifacts made available under licenses that Google explicitly does not accept. This is in line with the guidance provided on [Google Open Source’s documentation](https://opensource.google/documentation/reference/using/agpl-policy) on viral licenses such as GFDL.   


> Rationale Lacking … the rationales don't state reasons that I think a user would understand … 

We generally expect submissions to provide technical rationales for each site and have listed [requirements for what they should contain](https://github.com/GoogleChrome/related-website-sets/blob/main/RWS-Submission_Guidelines.md#set-formation-requirements), to support public review. However, in line with previous merge decisions we did not cite this as a reason for failure here.


> Not A Contribution: … My guess is that this would refer back the to “egregious and blatant disregard”

Updates to the RWS list are distributed to Chrome installations for browser consumption. We require contributors to this repository to agree to the CLA in order to grant Google the necessary rights to use their code contributions while retaining ownership of their contributions. By designating a communication as "NOT A CONTRIBUTION," an author can ensure that it isn’t treated as a submission to Google and therefore isn’t covered by the CLA. This is why we do not include communications marked as “NOT A CONTRIBUTION.”

Contributors are free to use the "NOT A CONTRIBUTION" designation as they see fit, usually to denote that specific communications with Google are not to be considered submissions subject to the CLA. But we can’t merge PRs that indicate that code changes are not covered by the CLA, which is the case with this PR.

> Opportunity to Fix: …

Many of these issues can be fixed by committing to the same PR, or creating a new PR. Either of those solutions would be reviewed on the following Tuesday to determine if the PR will be merged. [This is also addressed in the Quick-Start Guide](https://github.com/GoogleChrome/related-website-sets/blob/main/Getting-Started.md#debugging-failures). 

> Co-branding: … I am not clear on the need for co-branding.

Co-branding is one of several possible ways we outline as a possibility for associated sites to convey to users that they are related. Sites may not be co-branded as long as there is some other way that their relationship may be clear to their users. We did not verify co-branding of the sites in this PR, since we have not verified co-branding in other PRs either.

**Pull request closed without merging**
