### PR TITLE
Use unified diff format when reporting formatting issues

### PR DESCRIPTION
**Pull request by cfredric**
I think this will give more context (like line numbers) when reporting formatting differences, that should make it easier to know where the problems are.

### CODE REVIEW

**Comment by arichiv** [comment]
SGTM, does it work as expected when tested locally?

**Review by arichiv — APPROVED** [review]

**Comment by arichiv** [comment]
Looks like the tests need to be updated

**Comment by cfredric** [comment]
Hard to say if it works or not, since that depends on whether GitHub's markdown highlighter understands it. I'll make a test PR to see what it looks like after this merges to main.

**Comment by cfredric** [comment]
Confirmed, the highlighting worked fine. (It wasn't quite as pretty as I expected, but I think it's still better than not having any line numbers/context.)

**Review by limck5856 — APPROVED** [review]

**Pull request merged**
