### PR TITLE
Update related_website_sets.JSON

### PR DESCRIPTION
**Pull request by BgaborBP**

### CODE REVIEW

**Comment by cfredric** [comment]
If you'd like this PR to be reviewed, please sign the CLA and [mark this PR as ready for review](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/changing-the-stage-of-a-pull-request#marking-a-pull-request-as-ready-for-review).

**Comment by BgaborBP** [comment]
@cfredric thank you, we will mark this for review in a few days.

**Comment by cfredric** [comment]
Please see "Validation Success" here: https://github.com/GoogleChrome/related-website-sets/blob/main/RWS-Submission_Guidelines.md#subset-level-technical-validation

**Review by aselya — APPROVED** [review]
LGTM. merging

**Pull request merged**
